### PR TITLE
Remove hard-coded HTML strings

### PR DESCRIPTION
**Pull request by gumbarros**
**PR Title**
Remove hard-coded HTML strings

**PR Description**
Use a HtmlElement class to render all HTML content.

### CODE REVIEW

**Comment by LucioPelinson** [comment]
Breaking Changes
JJDataPanel properties (EnterKey, Layout, ShowViewModeAsStatic, FormCols) was moved to a Property UISettings
JJCombobox renamed Itens to Items

**Comment by gumbarros** [comment]
Breaking change
Renamed SizeTitle to TitleSize on JJGridView
Renamed TotalReg to TotalRecords on JJGridView
Renamed Erros to Errors on JJGridView

**Comment by gumbarros** [comment]
Breaking Changes JJGridView
Moved DoSqlCommand to ActionManager.ExecuteSqlCommand
Moved DoPythonScriptAction to ActionManager.ExecutePythonScriptAction

**Comment by LucioPelinson** [comment]
Breaking Change on JJLinkButton
Removed Property IsSubmit now use Type
Issue create to render action as a button 

```cs
public enum LinkButtonType
{
    Link = 0,
    Button = 1,
    Submit = 2
}
```

**Comment by gumbarros** [comment]
Breaking change on GridCellEventArgs
ResultHtml to HtmlResult

**Comment by gumbarros** [comment]
Breaking change on ActionEventArgs
 ResultHtml to HtmlResult

**Comment by gumbarros** [comment]
Breaking changes

Padronized all GridView public HTML to suffix with Html (correct english convention).
GridConfigSorting renamed to GridSortingConfig

**Comment by LucioPelinson** [comment]
Breaking change 
Renamed:
DataDictionaryManager to FormService
DataDictionaryManagerResult to FormLetter

**Comment by LucioPelinson** [comment]
this closes #28

**Pull request merged**
