### PR TITLE
Clone form element

### PR DESCRIPTION
**Pull request by gumbarros**

### CODE REVIEW

**Review by LucioPelinson — CHANGES_REQUESTED** [review]
In the test project, we need to have all objects instantiated and all fields set to ensure that the clone is working properly

**Comment by gumbarros** [comment]
> In the test project, we need to have all objects instantiated and all fields set to ensure that the clone is working properly

I already tested all reference types possible, value types are well tested using `MemberwiseClone`, added just `FormElementDataFile` that was missing.

**Review by LucioPelinson — CHANGES_REQUESTED** [review]
@gumbarros 
Simple properties such as ClassCss, Tooltip, FilterType are not being tested, all properties must be set to guarantee testing.
This change creates a major risk for systems that are running in a production environment.

**Comment by gumbarros** [comment]
> @gumbarros Simple properties such as ClassCss, Tooltip, FilterType are not being tested, all properties must be set to guarantee testing. This change creates a major risk for systems that are running in a production environment.

These are value types, are 100% handled by `MemberwiseClone()`, but I will make a new commit with all properties in a `FormElementField` to show you.

**Comment by gumbarros** [comment]
Added all possible value types for `FormElementField `and `BasicAction`

Commit a0485561f8090b7e574ddde8b01a33011fb3b347

**Pull request merged**
